name: test legacy install instructions for build-lambda-zip 
on:
  push:
    branches: 
      - main
  schedule:
    - cron: "7 7 * * *"
  pull_request: #temporary

jobs:
  thejob:
    runs-on: ${{ matrix.platform }}
    name: install build-lambda-zip on ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.12, 1.13]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: test install of build-lambda-zip using go ${{ matrix.go-version }}
        env:
          GOPROXY: direct
          GO111MODULE: on
        run: |
          go env
          go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip
