name: lint
on:
  pull_request:
jobs:
  lint:
    name: run golangci-golint on the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1'
      - uses: actions/checkout@v3
      - name: install golangci-golint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.48.0
      - run: ./bin/golangci-lint run -v ./...
       
